# Generated by Django 3.2.8 on 2022-06-30 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_type', models.CharField(max_length=200, null=True)),
                ('runs', models.IntegerField(blank=True, default=0, null=True)),
                ('fours', models.IntegerField(blank=True, default=0, null=True)),
                ('sixes', models.IntegerField(blank=True, default=0, null=True)),
                ('balls', models.IntegerField(blank=True, default=0, null=True)),
                ('catches', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_type', models.CharField(max_length=200, null=True)),
                ('overs', models.IntegerField(blank=True, default=0, null=True)),
                ('wickets', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('captain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_team', to='base.team')),
                ('to_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_team', to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('month', models.CharField(max_length=200, null=True)),
                ('day', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=200, null=True)),
                ('overs', models.IntegerField(blank=True, default=0, null=True)),
                ('batting1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting1', to='base.team')),
                ('batting2', models.ManyToManyField(blank=True, related_name='batting_stats2', to='base.BattingStat')),
                ('batting_stats1', models.ManyToManyField(blank=True, related_name='batting_stats1', to='base.BattingStat')),
                ('bowling1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling1', to='base.team')),
                ('bowling2', models.ManyToManyField(blank=True, related_name='batting_stats2', to='base.BowlingStat')),
                ('bowling_stats1', models.ManyToManyField(blank=True, related_name='bowling_stats1', to='base.BowlingStat')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='base.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='base.team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='base.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='game_invites',
            field=models.ManyToManyField(blank=True, related_name='game_invites', to='base.GameInvite'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team_invites',
            field=models.ManyToManyField(blank=True, related_name='team_invites', to='base.TeamInvite'),
        ),
    ]
