# Generated by Django 3.2.8 on 2022-06-30 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220630_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='batting_stats2',
            field=models.ManyToManyField(blank=True, related_name='batting_stats2', to='base.BattingStat'),
        ),
        migrations.AddField(
            model_name='game',
            name='bowling_stats2',
            field=models.ManyToManyField(blank=True, related_name='batting_stats2', to='base.BowlingStat'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='batting2',
        ),
        migrations.AddField(
            model_name='game',
            name='batting2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting2', to='base.team'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='bowling2',
        ),
        migrations.AddField(
            model_name='game',
            name='bowling2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling2', to='base.team'),
        ),
    ]
