# Generated by Django 3.2.8 on 2022-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220630_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bowling_stats2',
            field=models.ManyToManyField(blank=True, related_name='bowling_stats2', to='base.BowlingStat'),
        ),
    ]
