# Generated by Django 3.2.8 on 2022-07-01 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_game_bowling_stats2'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
