# Generated by Django 3.2.8 on 2022-07-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fifties',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
