# Generated by Django 3.2.8 on 2022-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_player_fifties'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='runs_hs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
