# Generated by Django 3.2.8 on 2022-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_player_runs_hs'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='runs_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
