# Generated by Django 3.2.8 on 2022-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220701_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balls_bowled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='balls_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wickets_hs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
