# Generated by Django 3.2.8 on 2022-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220701_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='games_won',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='runs_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wickets_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
