# Generated by Django 3.2.8 on 2022-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_player_filler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='filler',
        ),
        migrations.AddField(
            model_name='team',
            name='filler',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
