# Generated by Django 3.2.8 on 2022-07-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220702_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='day',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='month',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='overs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='games', to='base.Game'),
        ),
    ]
