# Generated by Django 3.2.8 on 2022-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220704_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battingstat',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='bowlingstat',
            name='out_type',
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='catches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battingstat',
            name='out_type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
