# Generated by Django 3.2.8 on 2022-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220705_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_batting_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team1_bowling_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_batting_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_bowling_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
