# Generated by Django 3.2.8 on 2022-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fours_hs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='sixes_hs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
