# Generated by Django 3.2.8 on 2022-07-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220707_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='gammes', to='base.Game'),
        ),
    ]
