# Generated by Django 4.0.5 on 2022-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220712_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='doneStats',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
