# Generated by Django 4.0.5 on 2023-08-31 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_post_remove_game_highlights_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('runs_scored', models.IntegerField(blank=True, default=0, null=True)),
                ('runs_ran', models.IntegerField(blank=True, default=0, null=True)),
                ('wicket', models.BooleanField(default=False, null=True)),
                ('wicket_type', models.CharField(max_length=200, null=True)),
                ('extras', models.IntegerField(blank=True, default=0, null=True)),
                ('ball_pitch', models.CharField(max_length=200, null=True)),
                ('ball_hit', models.CharField(max_length=200, null=True)),
                ('conclusion_statemet', models.CharField(max_length=200, null=True)),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ball_bowler', to=settings.AUTH_USER_MODEL)),
                ('non_strike_batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_strike_batsman', to=settings.AUTH_USER_MODEL)),
                ('on_strike_batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_strike_batsman', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('innings_num', models.IntegerField(blank=True, default=0, null=True)),
                ('current_ball', models.IntegerField(blank=True, default=0, null=True)),
                ('balls', models.ManyToManyField(blank=True, related_name='over_balls', to='base.ball')),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='over_bowler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bowlingstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='batting1',
            new_name='batting1_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='batting2',
            new_name='batting2_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='bowling1',
            new_name='bowling1_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='bowling2',
            new_name='bowling2_team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='batting_stats1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='batting_stats2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bowling_stats1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bowling_stats2',
        ),
        migrations.AddField(
            model_name='game',
            name='current_innings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='current_over',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='overs',
        ),
        migrations.DeleteModel(
            name='BattingStat',
        ),
        migrations.DeleteModel(
            name='BowlingStat',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='game',
            name='overs',
            field=models.ManyToManyField(blank=True, related_name='balls', to='base.ball'),
        ),
    ]
