# Generated by Django 4.0.5 on 2023-09-01 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_ball_over_remove_bowlingstat_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=200, null=True)),
                ('highlight', models.BooleanField(default=False, null=True)),
                ('extra', models.BooleanField(default=False, null=True)),
                ('extra_type', models.CharField(max_length=200, null=True)),
                ('batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_batsman', to=settings.AUTH_USER_MODEL)),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_bowler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_scored', models.IntegerField(blank=True, default=0, null=True)),
                ('runs_ran', models.IntegerField(blank=True, default=0, null=True)),
                ('wicket', models.BooleanField(default=False, null=True)),
                ('wicket_type', models.CharField(max_length=200, null=True)),
                ('extras', models.IntegerField(blank=True, default=0, null=True)),
                ('balls_batted', models.IntegerField(blank=True, default=0, null=True)),
                ('balls_bowled', models.IntegerField(blank=True, default=0, null=True)),
                ('fours', models.IntegerField(blank=True, default=0, null=True)),
                ('sixes', models.IntegerField(blank=True, default=0, null=True)),
                ('catches', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='over',
            name='balls',
        ),
        migrations.RemoveField(
            model_name='over',
            name='bowler',
        ),
        migrations.AddField(
            model_name='game',
            name='current_ball',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='overs',
        ),
        migrations.AddField(
            model_name='game',
            name='overs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='Over',
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_game', to='base.game'),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='players_stats',
            field=models.ManyToManyField(blank=True, related_name='players_stats', to='base.playergamestat'),
        ),
    ]
