# Generated by Django 4.0.5 on 2023-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_play_playergamestat_remove_over_balls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_innings',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
