# Generated by Django 4.0.5 on 2023-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_game_current_ball_alter_game_current_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestat',
            name='wicket',
        ),
        migrations.RemoveField(
            model_name='playergamestat',
            name='wicket_type',
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='runs_given_up',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='wickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
