# Generated by Django 4.0.5 on 2023-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_game_current_bowler_game_off_strike_batsman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestat',
            name='out_ball',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='out_over',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='playergamestat',
            name='out_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
