# Generated by Django 4.0.5 on 2023-09-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_playergamestat_out_ball_playergamestat_out_over_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ball1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ball2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ball3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ball4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ball5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='ball6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='playergamestat',
            name='out_type',
            field=models.CharField(default='not out', max_length=200, null=True),
        ),
    ]
