# Generated by Django 4.2.5 on 2023-09-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_game_ball1_game_ball2_game_ball3_game_ball4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='completed',
            new_name='entering_stats',
        ),
    ]
