# Generated by Django 4.2.5 on 2023-09-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_player_catches_average_player_centuries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='win_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
