# Generated by Django 4.2.5 on 2023-09-23 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_player_win_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='filler',
        ),
        migrations.AddField(
            model_name='team',
            name='temporary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_established', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=200, null=True)),
                ('games', models.ManyToManyField(blank=True, related_name='org_games', to='base.game')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organization'),
        ),
    ]
