# Generated by Django 4.2.5 on 2023-09-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_team_filler_team_temporary_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.organization'),
        ),
    ]
