# Generated by Django 4.2.5 on 2023-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_organizationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='org_invites',
            field=models.ManyToManyField(blank=True, related_name='org_invites', to='base.organizationinvite'),
        ),
    ]
