# Generated by Django 4.2.5 on 2023-09-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_player_org_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinvite',
            name='to_player',
        ),
    ]
