# Generated by Django 4.2.5 on 2023-09-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_organizationinvite_to_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
