# Generated by Django 4.2.5 on 2023-09-28 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_players',
            field=models.ManyToManyField(blank=True, related_name='team1_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_players',
            field=models.ManyToManyField(blank=True, related_name='team2_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
