# Generated by Django 4.2.5 on 2023-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_game_temporary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_players',
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='day',
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='month',
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='year',
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
