# Generated by Django 4.2.5 on 2023-10-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_game_team1_players_remove_game_team2_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='org_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_team', to='base.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='base.team'),
        ),
    ]
