# Generated by Django 4.2.5 on 2023-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_player_org_team_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='org_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='base.team'),
        ),
    ]
