# Generated by Django 4.2.5 on 2023-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_player_org_team_remove_player_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='org_teams', to='base.team'),
        ),
    ]
