# Generated by Django 4.2.5 on 2023-10-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_team_win_perecentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='win_perecentage',
            new_name='win_percentage',
        ),
    ]
