# Generated by Django 4.2.5 on 2023-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_message_chat_organization_chat_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='rules',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
