# Generated by Django 4.2.5 on 2023-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_chat_description_chat_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
